FROM node as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG REACT_APP_NAME
ENV REACT_APP_NAME=$REACT_APP_NAME
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html

# https://www.youtube.com/watch?v=3xDAU5cvi5E