version: "3"
services:
  react-app:
    # build: .
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
      args:
        - REACT_APP_NAME=myName_prod
    ports:
      - "8080:80"
    # env_file:
    #   - ./.env
